language: C
before_install:
 - sudo apt-get install valgrind
 
script:
 - make asgn
 - valgrind ./asgn -r The-Gift-of-the-Magi.txt < test10words.txt
 - ./checkstyle *.c *.h
 - ./asgn -p -s 7 mary.txt > testoutput1.txt
 - diff mary_output1.txt testoutput1.txt
 - ./asgn mary.txt -p -s 7 -r > testoutput2.txt
 - diff mary_output2.txt testoutput2.txt
 - gcov asgn.c


after_success:
 - bash <(curl -s https://codecov.io/bash)

